# Generated by Django 4.2 on 2023-04-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="article_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_name", models.CharField(max_length=50)),
                ("article_keywords", models.CharField(max_length=50)),
                ("article_abstract", models.CharField(max_length=350)),
                ("article_photo_path", models.CharField(max_length=100)),
            ],
        ),
    ]
