# Generated by Django 4.1.5 on 2023-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article_list",
            name="article_dates",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
