# Generated by Django 4.1.5 on 2023-04-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_article_list_article_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article_list",
            name="article_abstract",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="article_list",
            name="article_keywords",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="article_list",
            name="article_name",
            field=models.CharField(max_length=150),
        ),
    ]
