# Generated by Django 4.1.5 on 2023-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_article_list_article_abstract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article_list",
            name="article_abstract",
            field=models.CharField(max_length=1500),
        ),
    ]
