# Generated by Django 4.1.5 on 2023-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_article_list_article_abstract"),
    ]

    operations = [
        migrations.AddField(
            model_name="article_list",
            name="article_architecture_path",
            field=models.CharField(default="/static/brain.png", max_length=100),
        ),
        migrations.AddField(
            model_name="article_list",
            name="article_author",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="article_list",
            name="article_github",
            field=models.URLField(default="https://github.com/"),
        ),
        migrations.AddField(
            model_name="article_list",
            name="article_paper_link",
            field=models.URLField(default=""),
        ),
    ]
