# Generated by Django 4.2.3 on 2024-07-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('area', '0005_alter_area_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('AI', 'AI Team'), ('HW', 'Hardware Team')], default='HW', max_length=2)),
                ('pub_type', models.CharField(choices=[('CONF', 'Conference'), ('JOUR', 'Journal'), ('SURV', 'Survey')], default='JOUR', max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField(blank=True)),
                ('citation_text', models.TextField(blank=True)),
                ('published_date', models.DateTimeField()),
                ('doi_link', models.URLField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='upload/publications/%Y/%m/%d/')),
                ('pdf_link', models.URLField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('areas', models.ManyToManyField(blank=True, to='area.area')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='project.projects')),
            ],
        ),
    ]
