# Generated by Django 4.1.5 on 2024-01-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_projects_conferences_and_more"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="related_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="project.projects",
            ),
        ),
    ]
