# Generated by Django 4.2.3 on 2024-07-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_projects_architecture_path_and_more'),
        ('publications', '0003_publication_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='project.projects'),
        ),
    ]
