# Generated by Django 4.2.3 on 2024-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_member_list_team'),
        ('area', '0004_area_team'),
        ('publications', '0004_alter_publication_related_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='areas',
            field=models.ManyToManyField(blank=True, to='area.area'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(to='member.member_list'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='upload/publications/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
