# Generated by Django 4.1.5 on 2024-01-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publication", "0005_conference_rename_publication_list_journal"),
        ("area", "0001_initial"),
        ("member", "0010_member_list_hobby_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("areas", models.ManyToManyField(to="area.area")),
                (
                    "conferences",
                    models.ManyToManyField(blank=True, to="publication.conference"),
                ),
                ("members", models.ManyToManyField(to="member.member_list")),
                (
                    "project_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_lead",
                        to="member.member_list",
                    ),
                ),
                (
                    "publications",
                    models.ManyToManyField(blank=True, to="publication.journal"),
                ),
            ],
        ),
    ]
