# Generated by Django 4.2.3 on 2024-07-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0014_alter_member_list_team'),
        ('area', '0005_alter_area_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('AI', 'AI Team'), ('HW', 'Hardware Team')], default='HW', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('paper_link', models.URLField(blank=True, null=True)),
                ('other_link', models.URLField(blank=True, null=True)),
                ('areas', models.ManyToManyField(to='area.area')),
                ('members', models.ManyToManyField(to='member.member_list')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_lead', to='member.member_list')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='upload/project/%Y/%m/%d/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='project.projects')),
            ],
        ),
    ]
