# Generated by Django 4.2.3 on 2024-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_alter_area_photo'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='areas',
            field=models.ManyToManyField(blank=True, null=True, to='area.area'),
        ),
    ]
