# Generated by Django 4.1.5 on 2024-01-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="conferences",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="publications",
        ),
    ]
