# Generated by Django 4.2.3 on 2024-07-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projects_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='architecture_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='other_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='paper_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
