# Generated by Django 4.2.3 on 2024-07-18 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projects_description_alter_projects_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
