# Generated by Django 4.1.5 on 2024-01-11 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("history_date", models.DateTimeField(default=datetime.datetime.now)),
                ("description", models.TextField(blank=True, null=True)),
                ("photo", models.FileField(blank=True, upload_to="upload/%Y/%m/%d/")),
            ],
        ),
    ]
