# Generated by Django 4.1.5 on 2023-04-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awards_title", models.CharField(max_length=150)),
                ("award_dates", models.DateTimeField(blank=True, null=True)),
                ("awrad_contents", models.CharField(max_length=3000)),
                ("award_photo_path", models.CharField(max_length=100)),
            ],
        ),
    ]
