# Generated by Django 4.1.5 on 2023-06-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="awards",
            name="award_link",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
