# Generated by Django 4.1.5 on 2024-01-11 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0011_alter_member_list_hobby_photo_and_more"),
        ("awards", "0002_awards_award_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awards",
            name="award_photo_path",
        ),
        migrations.RemoveField(
            model_name="awards",
            name="awards_title",
        ),
        migrations.RemoveField(
            model_name="awards",
            name="awrad_contents",
        ),
        migrations.AddField(
            model_name="awards",
            name="contents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="awards",
            name="member",
            field=models.ManyToManyField(to="member.member_list"),
        ),
        migrations.AddField(
            model_name="awards",
            name="photo",
            field=models.FileField(blank=True, upload_to="upload/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="awards",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="awards",
            name="award_dates",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="awards",
            name="award_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
