# Generated by Django 4.2.3 on 2024-07-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_remove_awards_award_photo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='team',
            field=models.CharField(choices=[('AI', 'AI Team'), ('HW', 'Hardware Team')], default='HW', max_length=2),
        ),
    ]
