# Generated by Django 4.2.3 on 2024-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_awards_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='photo',
            field=models.FileField(blank=True, upload_to='upload/awards/%Y/%m/%d/'),
        ),
    ]
