# Generated by Django 4.2 on 2023-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_name", models.CharField(max_length=50)),
                ("pub_dates", models.DateTimeField(verbose_name="date published")),
                ("pub_author", models.CharField(max_length=200)),
                ("pub_photo_path", models.CharField(max_length=100)),
                ("pub_pdf_path", models.CharField(max_length=100)),
            ],
        ),
    ]
