# Generated by Django 4.1.5 on 2023-04-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0002_remove_publication_list_pub_photo_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication_list",
            name="pub_name",
            field=models.CharField(max_length=100),
        ),
    ]
