# Generated by Django 4.1.5 on 2023-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0003_alter_publication_list_pub_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication_list",
            name="pub_name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
