# Generated by Django 4.1.5 on 2023-06-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication", "0004_alter_publication_list_pub_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conf_name", models.CharField(max_length=150, unique=True)),
                ("conf_dates", models.DateTimeField(verbose_name="date published")),
                ("conf_author", models.CharField(max_length=200)),
                (
                    "conf_publisher",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("conf_pdf_path", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Publication_list",
            new_name="Journal",
        ),
    ]
