# Generated by Django 4.2.3 on 2024-07-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_conference_rename_publication_list_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='team',
            field=models.CharField(choices=[('AI', 'AI Team'), ('HW', 'Hardware Team')], default='HW', max_length=2),
        ),
        migrations.AddField(
            model_name='journal',
            name='team',
            field=models.CharField(choices=[('AI', 'AI Team'), ('HW', 'Hardware Team')], default='HW', max_length=2),
        ),
    ]
