# Generated by Django 4.1.7 on 2023-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="member_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_text", models.CharField(max_length=20)),
                ("ID_photo_path_text", models.CharField(max_length=100)),
            ],
        ),
    ]
