# Generated by Django 3.2.5 on 2023-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_list',
            name='one_sentence_text',
            field=models.CharField(default='Good, better, best', max_length=50),
        ),
    ]
