# Generated by Django 4.1.5 on 2023-06-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_list",
            name="degree",
            field=models.CharField(default="M.S. student", max_length=50),
        ),
        migrations.AddField(
            model_name="member_list",
            name="email",
            field=models.EmailField(default="@gachon.ac.kr", max_length=254),
        ),
    ]
