# Generated by Django 3.2.5 on 2023-04-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_list_one_sentence_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_list',
            name='second_photo_path',
            field=models.CharField(default='/static/brain.png', max_length=100),
        ),
    ]
