# Generated by Django 4.1.5 on 2023-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_member_list_degree_member_list_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_list",
            name="department",
            field=models.CharField(
                default="Department of Biomedical Engineering", max_length=50
            ),
        ),
    ]
