# Generated by Django 4.1.5 on 2023-11-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_member_list_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_list",
            name="status",
            field=models.CharField(
                choices=[("CU", "Current"), ("AL", "Alumni")],
                default="CU",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="member_list",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BS", "Bachelor"),
                    ("MS", "Master"),
                    ("PHD", "PhD"),
                    ("PD", "Postdoc"),
                    ("PR", "Professor"),
                ],
                default="MS",
                max_length=50,
            ),
        ),
    ]
