# Generated by Django 4.1.5 on 2023-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0004_member_list_status_alter_member_list_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member_list",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BS", "Bachelor"),
                    ("MS", "Master"),
                    ("PHD", "PhD"),
                    ("PD", "Postdoc"),
                    ("PR", "Professor"),
                    ("CA", "Co-Advisor"),
                ],
                default="BS",
                max_length=50,
            ),
        ),
    ]
