# Generated by Django 4.2.7 on 2023-11-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_rename_second_photo_path_member_list_hobby_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_list',
            name='degree',
            field=models.CharField(choices=[('CA', 'Co-Advisor'), ('PR', 'Professor'), ('PD', 'Postdoc'), ('PHD', 'PhD'), ('MS', 'Master'), ('BS', 'Bachelor')], default='BS', max_length=50),
        ),
    ]
