# Generated by Django 4.1.5 on 2023-11-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0007_alter_member_list_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member_list",
            name="name",
            field=models.CharField(default="Name", max_length=20),
        ),
    ]
