# Generated by Django 4.1.5 on 2023-12-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0008_alter_member_list_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="member_list",
            name="main_photo",
            field=models.FileField(blank=True, upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
