# Generated by Django 4.1.5 on 2024-01-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0011_alter_member_list_hobby_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member_list",
            name="hobby_photo_path",
        ),
        migrations.RemoveField(
            model_name="member_list",
            name="main_photo_path_text",
        ),
        migrations.AlterField(
            model_name="member_list",
            name="motto",
            field=models.CharField(default="No data", max_length=50),
        ),
    ]
