# Generated by Django 4.2.3 on 2024-07-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_alter_member_list_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_list',
            name='degree',
            field=models.CharField(choices=[('CA', 'Co-Advisor'), ('PR', 'Professor'), ('RS', 'Researcher'), ('PD', 'Postdoc'), ('PHD', 'PhD'), ('MS', 'Master'), ('BS', 'Bachelor')], default='BS', max_length=50),
        ),
        migrations.AlterField(
            model_name='member_list',
            name='name',
            field=models.CharField(default='Name', max_length=255),
        ),
    ]
