# Generated by Django 4.2.3 on 2025-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_alter_member_list_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_list',
            name='motto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
