version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8000"  # 변경된 포트
    volumes:
      - .:/app
    environment:
      - DEBUG=1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
