# Generated by Django 4.1.5 on 2024-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="photo",
            field=models.FileField(blank=True, upload_to="upload/area/%Y/%m/%d/"),
        ),
    ]
