# Generated by Django 4.1.5 on 2024-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area", "0002_area_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="photo",
            field=models.FileField(blank=True, upload_to="upload/%Y/%m/%d/"),
        ),
    ]
