# Generated by Django 4.1.5 on 2023-04-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="photo_dates",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
