# Generated by Django 4.2.3 on 2024-07-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_gallery_photo_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='team',
            field=models.CharField(choices=[('AI', 'AI Team'), ('HW', 'Hardware Team')], default='HW', max_length=2),
        ),
    ]
