# Generated by Django 4.2.3 on 2024-07-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('AI', 'AI Team'), ('HW', 'HW Team')], default='AI', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('research_fields', models.TextField(blank=True, null=True)),
                ('lab_location', models.CharField(max_length=200)),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('introduction', models.TextField()),
                ('keywords', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='upload/advisor_photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_experiences', to='advisor.advisor')),
            ],
        ),
    ]
