# Generated by Django 4.2.3 on 2024-07-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='title',
        ),
    ]
