# Generated by Django 4.1.5 on 2023-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history_title", models.CharField(max_length=20)),
                ("history_dates", models.DateTimeField(blank=True, null=True)),
                (
                    "history_photo_path",
                    models.CharField(default="/static/brain.png", max_length=100),
                ),
            ],
        ),
    ]
