# Generated by Django 4.1.5 on 2023-04-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="history_title",
            field=models.CharField(max_length=100),
        ),
    ]
